### ISSUE TITLE
Using the ./setup

### ISSUE THREAD

**Issue by liamgreen** [jprjr/multistreamer-installer#1]
Right so i was going to reply to you via eMail. But i thought that it would be more convient for me to post it all on this git since it's todo with this one. Also means if anyone else get's these problems you can send them to this issuie thread and they can have a good read. Hope that is all okay with you :)

Looked into the temp folder and this has happened.

```make[2]: Leaving directory '/src/openresty-1.11.2.4/build/nginx-1.11.2'
make[1]: Leaving directory '/src/openresty-1.11.2.4/build/nginx-1.11.2'
mkdir -p /opt/openresty-1.11.2.4-rtmp/site/lualib /opt/openresty-1.11.2.4-rtmp/site/pod /opt/openresty-1.11.2.4-rtmp/site/manifest
ln -sf /opt/openresty-1.11.2.4-rtmp/nginx/sbin/nginx /opt/openresty-1.11.2.4-rtmp/bin/openresty
~/multistreamer-installer
./install: line 83: opt/openresty-1.11.2.4-rtmp: No such file or directory```

**Comment by jprjr** [comment]
Weird! Try doing a `git pull origin master` and give it another try

**Comment by liamgreen** [comment]
Here is another problem. Normally when installing these items a GUI appears and I press enter to click "okay" but for some reason, the GUI hasn't appeared so can't do it so the installer has stopped. 

`(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 28060 files and directories currently installed.)
Preparing to unpack .../libc6_2.23-0ubuntu9_amd64.deb ...
[?1049h[1;24r(B[m[4l[?7h[H[2J[?1049l[H[2J[?1h=[?1000h[39;49m[?1h=[19d(B[0;1m[36m[44m[J[H Package configuration[K
 (0[0;1m[36m[44mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq(B[0;1m[36m[44m[K
[K
[K
[K
[K
 (0[0;1m[37m[47mlqqqqqqqqqqqqqqqqqqqqqqqqqqq(B[0;1m[34m[47mConfiguring libc6(0[0;1m[37m[47mqqqqqqqqqqqqqqqqqqqqqqqqqqqqq(0[0m[30m[47mk(B[0;1m[36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[73X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[73X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[73X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[73X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[73X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[73X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[73X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mtqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq(0[0m[30m[47mu(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mx(B[0m[30m[47m[31X[16;34H(B[0;1m[37m[44m<[33m[44m  [37m[44mO[33m[44mK  [37m[44m>(B[0m[30m[47m[34X[76G(0[0m[30m[47mx(B[0;1m[30m[40m  [36m[44m[K
 (0[0;1m[37m[47mm(0[0m[30m[47mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj(B[0;1m[30m[40m  [36m[44m[K
   [30m[40m[75X[79G[36m[44m[K[16;37H[39;49m(B[m[8;4H[30m[47mKernel version not supported

[4GThis version of the GNU libc requires kernel version 3.2 or later.
[4GOlder versions might work but are not officially supported. Please
[4Gconsider upgrading your kernel.[16;37H[39;49m(B[m`

**Comment by liamgreen** [comment]
Oh i left it alone and the installer seems to off carried on
![screenshot](https://user-images.githubusercontent.com/1432485/29623984-e8d32d44-881f-11e7-81e5-849121304ab0.PNG)

**Comment by liamgreen** [comment]
When I run "postgres-auth-server add " this happens. 
![screenshot](https://user-images.githubusercontent.com/1432485/29625628-33bbad46-8824-11e7-9a3d-4757af3ece05.PNG)

**Comment by liamgreen** [comment]
I even made the folder up and made a shortcut link to that config file 
![screenshot](https://user-images.githubusercontent.com/1432485/29626503-cc3d1792-8826-11e7-853d-706228a3688a.PNG)

and is still showing the same error message

**Comment by liamgreen** [comment]
Right so i've just copied the file into that folder and now it says 
![screenshot](https://user-images.githubusercontent.com/1432485/29626632-428a1242-8827-11e7-83e6-161a61bce2be.PNG)

**Comment by jprjr** [comment]
Hmm. The setup script should have made `/etc/postgres-auth-server/config.yaml` with all the right settings for you.

Also in your screenshot, you have it named `config.yalm` but it should be `config.yaml`

The example file won't work by default, it doesn't have any information on how to connect to postgres. I'd delete `/etc/postgres-auth-server/config.yaml` and try running setup again, it should create it

**Comment by liamgreen** [comment]
Yeah, i fixed the file name. And okay I've deleted it and now I'm running the set up again

**Comment by liamgreen** [comment]
![screenshot](https://user-images.githubusercontent.com/1432485/29630326-c0e58034-8833-11e7-9a3e-178b68bcb03d.PNG)

**Comment by jprjr** [comment]
`./install` strictly does an install - but no setup whatsoever, it just handles downloading modules, compiling openresty, etc

`./setup` will do everything `./install` does, but also automatically create config files, setup an nginx reverse proxy, etc - try running `./setup (hostname)` - replace "hostname" with your DNS hostname

**Comment by liamgreen** [comment]
You know something. I need to get my eyes checked again (i'm wearing glasses) as you're totally right. I'm doing the set up now.

**Comment by liamgreen** [comment]
![capture1](https://user-images.githubusercontent.com/1432485/29632045-96ee9a62-8839-11e7-8305-1d9d14ef54a4.PNG)
![screenshot](https://user-images.githubusercontent.com/1432485/29632046-97046234-8839-11e7-9c49-f3c7fe9f72de.PNG)

I haven't got a clue what's going on. There's no files in the OPT folder. I'm going to make a VPS on digitalocean and see if it works on there. and if it does then i know what's going on.

**Comment by liamgreen** [comment]
Right, Update: It's worked without a problem and is installed. 
![screenshot](https://user-images.githubusercontent.com/1432485/29633411-1d9c907e-883e-11e7-9ba8-806d76cc2d2e.PNG)

How do I fix this problem? I'm new to SSL

**Comment by jprjr** [comment]
One of the final steps it does is gets SSL certs from Let's Encrypt, it looks like that didn't happen.

Did it print "SUCCESS" at the end?

**Comment by liamgreen** [comment]
![screenshot](https://user-images.githubusercontent.com/1432485/29633769-463a42d2-883f-11e7-95dd-8daa562bb75e.PNG)

**Comment by jprjr** [comment]
Interesting. Try `service nginx restart`, maybe the reload just didn't take for some reason

**Comment by liamgreen** [comment]
Done that and still the same problem.

**Comment by jprjr** [comment]
Just tried pulling up https://development.obinx.com - worked fine for me, maybe your browser isn't setup to accept Let's Encrypt certificates? I thought most of them were nowadays, I know Firefox and Chrome should work fine

**Comment by liamgreen** [comment]
Arhh must be my browser waiting to update.. I'm using chrome. Glad it works :)

**Comment by jprjr** [comment]
Well, in the screenshot above I saw an error configuring nginx.

I only tested from a minimal install of Ubuntu (and I know off the topof my head that DigitalOcean does a minimal install).

I'm guessing your other VPS already has Apache/PHP/etc setup and made nginx fail to get setup. If they have an option for rebuilding a minimal install of Ubuntu, it'll probably work

**Comment by jprjr** [comment]
Yeah, I think that was the problem. I just did an update for the script to try disabling apache2 *before* installing nginx, that should keep that from being a problem

**Comment by liamgreen** [comment]
Okay will give it a try. Also 
![screenshot](https://user-images.githubusercontent.com/1432485/29634672-878b68e4-8842-11e7-9ca4-747d6e66954d.PNG)

**Comment by jprjr** [comment]
Oh weird, they every "minimal" installs for everything except 16.04 it looks like? Lame, haha!

**Comment by liamgreen** [comment]
I know right. The VPS is only $12 a year hahaha. I'm going to rebuild the VPS and try the script again. I've also emailed support. See what they have to say

**Comment by liamgreen** [comment]
![screenshot](https://user-images.githubusercontent.com/1432485/29634902-34d3e792-8843-11e7-9664-7f54e13a3bfe.PNG)
Let's see if it all works :)

**Comment by liamgreen** [comment]
They have sent me this response back. 

"There isn't a minimal version of Ubuntu 16.04, unfortunately. There is, however, a Minimal version of 14.04 if that would work for you?"

**Comment by jprjr** [comment]
I wouldn't worry about it - hopefully it will work with the default 16.04 now that I disable apache early on

**Comment by liamgreen** [comment]
![screenshot](https://user-images.githubusercontent.com/1432485/29636626-4201a016-8849-11e7-86c4-d3fc5ad8fa25.PNG)
Stuck on here.

**Comment by jprjr** [comment]
How long have you let it go for? I don't see any errors setting up nginx, and that lost of packages can sometimes take a while, especially if you happen to hit a slow mirror

**Comment by liamgreen** [comment]
Around 1 hour ago.

**Comment by jprjr** [comment]
What does /tmp/tmp.pkQDGp66Sv show?

**Comment by liamgreen** [comment]
"Cloning/updating setup-openresty script (details in /tmp/tmp.pkQDGp66Sv)
Cloning into '/opt/setup-openresty'..."

**Comment by jprjr** [comment]
If you wanna try again, the `setup-openresty` script should output the package-installation to the terminal

**Comment by liamgreen** [comment]
Since I'm messing around. Going to try Ubuntu 14.04 Min

**Comment by liamgreen** [comment]
![screenshot](https://user-images.githubusercontent.com/1432485/29638611-af486e42-884f-11e7-8eb5-175c2d3b767c.PNG)

Nope doesn't want to work. Will try 16.04 again in a moment.

**Comment by liamgreen** [comment]
![screenshot](https://user-images.githubusercontent.com/1432485/29639348-55f2e00e-8852-11e7-9382-b412d5d9f8fb.PNG)

if you go to the domain development.obinx.com what does it show?

**Comment by liamgreen** [comment]
So I ran the ./setup command again and it's done this. 
![screenshot](https://user-images.githubusercontent.com/1432485/29639459-b9ceee4c-8852-11e7-960d-3b929b66f434.PNG)

**Comment by liamgreen** [comment]
When I go to /users and add a user and then go to /login it doesn't work.

**Comment by liamgreen** [comment]
When I go to /users and add a user and then go to /login it doesn't work.
![screenshot](https://user-images.githubusercontent.com/1432485/29639879-4287d46e-8854-11e7-945b-b45e0e8c68fe.PNG)
Do I need to do anything with the above?

**Comment by jprjr** [comment]
Does /users/login work with the new user?

You don't need to do anything with that screenshotted file

**Comment by liamgreen** [comment]
Nope, it does not. Tried to create a user with "test" and "123456789" and didn't login.

**Comment by jprjr** [comment]
Shoot me an email with some login details and I'll take a look

**Comment by liamgreen** [comment]
Sent email

**Comment by jprjr** [comment]
Turns out I had a bug with creating users in the web interface - give it a try now, it should all work

**Comment by liamgreen** [comment]
Fantastic, all works :) Wahooooo
