### ISSUE TITLE
How do I add Facebook APP, Youtube, etc using ./setup <domain>?

### ISSUE THREAD

**Issue by danielrodrigotest** [jprjr/multistreamer-installer#14]
Hi jprjr...I found amazing your script, but I could not add YouTube and Facebook Accounts into the page. In fact, I made a fresh install and using your script Multistreamer-installer. How do I add these accounts with a command or where can I manually add these accounts?
I really hope to receive an answer.

Thanks
![Screenshot 2019-07-17 at 2 27 10 AM](https://user-images.githubusercontent.com/40525323/61352065-67874a80-a83a-11e9-993d-722af3219fe4.png)

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
