### ISSUE TITLE
Adding Users. 

### ISSUE THREAD

**Issue by liamgreen** [jprjr/multistreamer-installer#3]
When I go to add users. It add's them but then won't let me log in. 

Update #1: I can login via the main account that was created via the ./setup process. 
Update #2: If i use the command "postgres-auth-server add (username)" it adds the user

**Comment by liamgreen** [comment]
I'm still having this problem. Also can you tell me what files i'd edit to edit the /users page.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
