### ISSUE TITLE
Install so not FFMPEG

### ISSUE THREAD

**Issue by tomasguirao** [jprjr/multistreamer-installer#4]
Hi,
I install with script and its all ok, but, in app dont appear option to ffmpeg arguments for custom RTMP
Could you help me?
thank you

**Comment by jprjr** [comment]
When you use this installer, custom ffmpeg arguments are disabled (since it can potentially allow users to use a lot of resources), you need to explicitly turn them on.

Take a look at `/opt/multistreamer/config.lua` and look for:

```
  -- allow/disallow transcoding (default: true)
  allow_transcoding = false,
  -- allow/disallow creating pullers (default: true)
  allow_custom_puller = false,
```

And turn on features accordingly
