### ISSUE TITLE
Install script not run

### ISSUE THREAD

**Issue by tomasguirao** [jprjr/multistreamer-installer#5]
Hi,
I´m trying to install with script on ubuntu 16.04 on VPS but not run..
![image](https://user-images.githubusercontent.com/4302292/33014953-538ed0de-cde9-11e7-8754-95cd70deb8de.png)
 this is multistreamer status
Could you help me...
thank you

**Comment by tomasguirao** [comment]
I´m trying install with script ./install and ./setup but not run.. 
I install on Ubuntu 16.04 simple install. Must I install something before?
tahnk you

**Comment by jprjr** [comment]
You don't need to run both `install` and `setup`, you run one or the other. `setup` will run `install` for you.

`install` sets up OpenResty, Multistreamer, Sockexec, and postgres-auth-server

`setup` will do everything `install` does, but also setup nginx, Let's Encrypt, etc.

**Comment by tomasguirao** [comment]
yes, I know..
I do ./setup and script do evething... but not run.
When script install nginx, run but after finnish not run...
