### ISSUE TITLE
Succes but error..

### ISSUE THREAD

**Issue by tomasguirao** [jprjr/multistreamer-installer#6]
I´m install on VPS ubuntu 16.04. It install fine, and say SUCESS but dont work.
say that:

## Getting Let's Encrypt certificates...
/opt/openresty-rtmp/luajit/bin/luajit: /opt/multistreamer/lib/multistreamer/config.lua:2: module 'lyaml' not found:
        no field package.preload['lyaml']
        no file '/opt/multistreamer/lib/lyaml.lua'
        no file '/opt/multistreamer/lib/lyaml/init.lua'
        no file '/opt/multistreamer/lua_modules/share/lua/5.1/lyaml.lua'
        no file '/opt/multistreamer/lua_modules/share/lua/5.1/lyaml/init.lua'
        no file './lyaml.lua'
        no file '/opt/multistreamer/lua_modules/lib/lua/5.1/lyaml.so'
stack traceback:
        [C]: in function 'require'
        /opt/multistreamer/lib/multistreamer/config.lua:2: in main chunk
        [C]: in function 'require'
        /opt/multistreamer/lib/multistreamer/cli.lua:4: in main chunk
        [C]: in function 'require'
        /opt/multistreamer/bin/multistreamer.lua:3: in main chunk
        [C]: at 0x00404b60
## Enabling and starting sockexec, postgres-auth-server, multistreamer...

**Comment by jprjr** [comment]
Oh shoot, this script is installing the latest release (11.something), which requires a few new modules. I'll get that fixed shortly

**Comment by tomasguirao** [comment]
Ok thank you!
Notify when this fixed

**Comment by jprjr** [comment]
This should be fixed - try pulling it down and running

**Comment by tomasguirao** [comment]
Hello jprjr,
error:
## Generating multistreamer config file (/opt/multistreamer/config.lua) ...
./setup: 346: ./setup: cannot create /etc/multistreamer/config.yaml: Directory nonexistent

I try create directory but:
error: 
## Generating multistreamer config file (/opt/multistreamer/config.lua) ...
grep: /opt/multistreamer/config.lua: No such file or directory

**Comment by jprjr** [comment]
Crud, sorry, I didn't thoroughly test the `setup` script (that requires me creating a new CNAME dns record for LetsEncrypt).

Let me get a droplet spun up and give it a thorough run-though

**Comment by tomasguirao** [comment]
install script have error too:

 ./install

root@Ubuntu-1604-xenial-64-minimal ~ # postgres-auth-server add
Unable to find config file. Searched paths:
/etc/postgres-auth-server/config.yaml

root@Ubuntu-1604-xenial-64-minimal ~/multistreamer-installer # journalctl -xe

Jan 08 14:22:43 Ubuntu-1604-xenial-64-minimal postgres-auth-server[22377]: Unable to find config file. Searched paths:
Jan 08 14:22:43 Ubuntu-1604-xenial-64-minimal postgres-auth-server[22377]: /etc/postgres-auth-server/config.yaml
Jan 08 14:22:43 Ubuntu-1604-xenial-64-minimal systemd[1]: postgres-auth-server.service: Control process exited, code=exited status=1
Jan 08 14:22:43 Ubuntu-1604-xenial-64-minimal systemd[1]: Failed to start postgres-auth-server.
-- Subject: Unit postgres-auth-server.service has failed

**Comment by jprjr** [comment]
Yeah, since it was looking for the config file at `/opt/multistreamer/config.lua` instead of `/etc/multistreamer/config.yaml`, it failed to create the config file for postgres-auth-server. I've got some updates pushed and I'm testing them out now.

I really need to find a way to setup a LetsEncrypt-compatible service for internal domains, it would make testing this way, way simpler

**Comment by jprjr** [comment]
Just pushed an update, everything should work correctly now.

**Comment by tomasguirao** [comment]
fine! perfect!
./setup install and setup like a clamp.  
Congratulations!
only one problem.. Stream preview not working.,, It detect signal because go button is actived but dont preview image...
